"""Changed charityproject to charity_project

Revision ID: 1957513ff1cb
Revises: 1e221f849d17
Create Date: 2023-08-17 20:13:19.914480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1957513ff1cb'
down_revision = '1e221f849d17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
