"""Updated full_amount type

Revision ID: 1e221f849d17
Revises: a54641171c90
Create Date: 2023-08-17 19:39:28.858828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e221f849d17'
down_revision = 'a54641171c90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
