"""Updated GET of Donations

Revision ID: 2ec0143a2dbd
Revises: c124fe516ba0
Create Date: 2023-08-17 23:09:36.300891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ec0143a2dbd'
down_revision = 'c124fe516ba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
