"""Updated imports

Revision ID: c124fe516ba0
Revises: 1957513ff1cb
Create Date: 2023-08-17 20:24:12.124137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c124fe516ba0'
down_revision = '1957513ff1cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
